name: "Run Server Tests"

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: dart-lang/setup-dart@v1.3

      - name: Convert Firebase Secret to file
      - uses: devops-actions/json-to-file@v1.0.0
        with:
          json: ${{ secrets.ADMIN_SDK_STR }}
          filename: 'firebase_config.json'

      #   id: create_firebase_admin_sdk_json
      #   uses: ttd2089/secret-file-action@1.0.0
      #   env:
      #     secret: ${{ secrets.ADMIN_SDK_STR }}

      - name: Install dependencies
        run: dart pub get

      - name: Analyze project source
        run: dart analyze

      - name: Run tests
        run: dart test
        env:
          # ADMIN_SDK_FILE_PATH: ${{ steps.create_firebase_admin_sdk_json.outputs.file }}
          ADMIN_SDK_FILE_PATH: 'firebase_config.json'
          IS_DEBUG: false